In [1]:
import numpy as np
import pandas as pd

### Membuat series (pd.Series)

In [2]:
pd.Series([ 11, 12, 13, 14])

0    11
1    12
2    13
3    14
dtype: int64

In [3]:
pd.Series([1.0, 2.1, 3.0, 4.0])

0    1.0
1    2.1
2    3.0
3    4.0
dtype: float64

### banyak type data menjadi object

In [5]:
pd.Series([1, 2.1, 3, 4.0, 'ilyas']) #maka index deafault 0 1 2 3 ...

0        1
1      2.1
2        3
3      4.0
4    ilyas
dtype: object

### memasukkan ke variabel

In [6]:
revenues = pd.Series([1, 2.1, 3, 4.0, 'ilyas'])

In [7]:
revenues

0        1
1      2.1
2        3
3      4.0
4    ilyas
dtype: object

In [8]:
revenues.values #menampilan values saja .values

array([1, 2.1, 3, 4.0, 'ilyas'], dtype=object)

In [9]:
revenues.index

RangeIndex(start=0, stop=5, step=1)

### Membuat series dengan index

In [2]:
number_revenues = pd.Series(
    [111, 222, 333],
    index=["number_1", "number_2", "number_3"]
)

In [3]:
number_revenues

number_1    111
number_2    222
number_3    333
dtype: int64

### Coba pake dictionaries {},kal tadi kan list[],satunya tuple/function()
## {} selalu punya pasangan key:value misal {'number_1':1}

In [4]:
number_revenues_1 = pd.Series({'number_1': 11, 'number_2':22, 'number_3':33})
number_revenues_1

number_1    11
number_2    22
number_3    33
dtype: int64

In [5]:
number_revenues_1.values

array([11, 22, 33], dtype=int64)

In [7]:
number_revenues_1.index

Index(['number_1', 'number_2', 'number_3'], dtype='object')

In [8]:
number_revenues_1.keys()

Index(['number_1', 'number_2', 'number_3'], dtype='object')

### Cek apakah values yang ingin di cari ada dengan  indexnya
## pake syntax in

In [9]:
"number_1" in number_revenues_1

True

### DATA FRAME
## pd.DataFrame()

In [11]:
# coba buat dataframe pake dictionaries {}
tabel_penomoran = pd.DataFrame({
                    "penomoran ke 1": number_revenues,      #penomoran ke 1 jadi kolom 1
                    "penomoran ke 2": number_revenues_1     # number_revenues jadi bari kebawah pengisi kolom penomoran 1
})
tabel_penomoran

penomoran ke 1  penomoran ke 2
number_1             111              11
number_2             222              22
number_3             333              33

In [12]:
# index yang sama jadi satu atau melebur
tabel_penomoran.index

Index(['number_1', 'number_2', 'number_3'], dtype='object')

In [13]:
tabel_penomoran.values

array([[111,  11],
       [222,  22],
       [333,  33]], dtype=int64)

### NOTE
## Membaca nama_tabel.values

## misal muncul 4.2e+3

## 4.2e+3 = 4.2 x 10^3
## 4.2e-3 = 4.2 x 10^-3

## axes[ o] = baris pertama index
## axes[ 1]= deretan nama kolom 


In [14]:
tabel_penomoran.axes[0]

Index(['number_1', 'number_2', 'number_3'], dtype='object')

In [15]:
tabel_penomoran.axes[1]

Index(['penomoran ke 1', 'penomoran ke 2'], dtype='object')

In [16]:
tabel_penomoran.columns # cek colum sama persis tabel_penomoran.axes[1]

Index(['penomoran ke 1', 'penomoran ke 2'], dtype='object')

In [17]:
"number_1" in tabel_penomoran

False

In [19]:
"penomoran ke 1" in tabel_penomoran

True

### in di data series merujuk ke index
### kalo in di dataframe merujuk ke kolom 

In [20]:
number_revenues

number_1    111
number_2    222
number_3    333
dtype: int64

In [21]:
number_revenues[1:]

number_2    222
number_3    333
dtype: int64

In [22]:
number_revenues[-1]

333

### .loc .iloc ([])
## .log(label) -> terlihat
## .ilog(buat index) -> index default tak terlihat dimulai 0 1 2 3 ...

In [24]:
colors = pd.Series(
    ["red","blue","black","yellow","green"],
    index=[1,2,3,5,8]
)
colors

1       red
2      blue
3     black
5    yellow
8     green
dtype: object

In [30]:
colors[1] #index/label terlihat

'red'

In [28]:
colors.loc[1] #index/label terlihat

'red'

In [27]:
colors.iloc[1] #index/label default tak terlihat 0 1 2 3 ..

'blue'

In [31]:
colors.loc[3:8]

3     black
5    yellow
8     green
dtype: object

In [33]:
colors.iloc[3:]

5    yellow
8     green
dtype: object

In [34]:
colors.iloc[-2] #kalo colors.loc[-2] error
                # menampilkan keyError -> penulisan salah atau data yang dicari naN 

'yellow'

### .iloc dipake di list
### .loc pake di dictionaries

In [36]:
tabel_penomoran

penomoran ke 1  penomoran ke 2
number_1             111              11
number_2             222              22
number_3             333              33

In [38]:
tabel_penomoran["penomoran ke 1"]

number_1    111
number_2    222
number_3    333
Name: penomoran ke 1, dtype: int64

In [41]:
tabel_penomoran["penomoran ke 2"]

number_1    11
number_2    22
number_3    33
Name: penomoran ke 2, dtype: int64

### .loc [ : ]
##          [rows apa: column apa] 
## ctt: .loc cuma nerima 2 parameters 
## ngakalin dimasukkan list

## misal city_data.loc["number_1":"number_2", ["isi", "isi", "isi"]]

### GABUNGIN belajar sendiri kode.id 
## pd.concat
## jangan lupa sort=False ,ga disorting atau ga diurutin
## kebawah, colomn sama persis

### gabungin kesamping
## pake axis=1 ,liat kode.id ae bang