### import

In [1]:
#import

import coba_import
coba_import.name

'ilyas'

### from

In [2]:
from coba_import import name, huruf
name

'ilyas'

### inisialisasi

In [3]:
from coba_import import name as n, huruf as h
n

'ilyas'

### ambil package

In [2]:
import coba_ambil_pkg.mod_1, coba_ambil_pkg.mod_2
coba_ambil_pkg.mod_1.name

'file pkg 1'

### Numpy

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.ones(2)

array([1., 1.])

In [7]:
print(np.arange(2,10,2))
print(np.arange(2))

[2 4 6 8]
[0 1]


In [9]:
height = [1.73, 1.68, 1.53]
weight = [57.4, 68.1, 53.1]

np_height= np.array(height)
np_weight= np.array(weight)

np_weight/np_height**2

array([19.17872298, 24.12840136, 22.68358324])

In [11]:
height = np.array([1.73, 1.68, 1.53])
weight = np.array([57.4, 68.1, 53.1])
weight/height**2

array([19.17872298, 24.12840136, 22.68358324])

In [12]:
arr = np.array([1,2,3,4,5])
np.append(arr, [6,7,8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
p = np.array([10, 99, 88])
l = np.array([9, 1, 0])
lu= p*l
print(lu)

[90 99  0]


In [16]:
np.delete(arr, 2)

array([1, 2, 4, 5])

In [17]:
np.sort(arr)

array([1, 2, 3, 4, 5])

### size, dimensi, dll

In [19]:
array_1 = np.array([[
    [1,2,3,4,5,],
    [6,7,8,9,10],
    [11,12,13,14,15]
]])

print(array_1)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [21]:
array_1.ndim #hasil 3 dimensi


3

In [25]:
#cari size/ jumlah data yang ada didalam array
array_1.size

15

In [22]:
scalar = np.array(32)
print(scalar)

32


In [30]:
vektor = np.array([32, 64, 128]) # 1 dimensi
print(vektor)
print(vektor.ndim)

[ 32  64 128]
1


In [31]:
matriks = np.array([[32, 64, 128],
                    [32, 64, 128]]) # 2 dimensi
print(matriks)
print(matriks.ndim)

[[ 32  64 128]
 [ 32  64 128]]
2


### ubah 1 dimensi ke beberapa dimensi

In [33]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [34]:
b = a.reshape(3,2) #dimensi sesuai request
print(b)

[[0 1]
 [2 3]
 [4 5]]


### newaxis dll, lanjut belajar sendiri boii, badan mengcape

### LATIHAN DULU BOI

In [37]:
a = np.arange(2,11).reshape(3,3) # 2 dimensi
print(a)
print(a.shape)
print(a.ndim)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
(3, 3)
2


In [39]:
arr = np.array(70)
print(arr.ndim)

0


In [40]:
arr = np.array([[
    [1,2,3],
    [1,2,3],
    [1,2,3],
    [1,2,3]
]])
print(arr)
arr.shape

[[[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]]


(1, 4, 3)

In [43]:
arr = np.array([[
    [1,2,3,4],
    [1,2,3,4]
    
]])
print(arr)
#arr.shape
arr.ndim

[[[1 2 3 4]
  [1 2 3 4]]]


3

In [48]:
arr = np.array([[
    [1,2,3,4],
    [1,2,3,4],

    [1,2,3,4],
    [1,2,3,4]
    
]], ndmin=4)
print(arr)
#arr.shape
arr.ndim

[[[[1 2 3 4]
   [1 2 3 4]
   [1 2 3 4]
   [1 2 3 4]]]]


4

In [51]:
a = np.array([3,2,1,1])

print(a[3]+a[2])


2


In [54]:
a = np.array([[3,2,1,1],[3,2,1,1]])

print(a[1,3])


1


In [68]:
a = np.array([[[1,2,3],[4,5,6]],
                [[7,8,9],[10,11,12]
]])
print(a[:1,1,1])
#print(a.shape)

[5]


In [69]:
print(a[:2,1,1])

[ 5 11]


In [70]:
print(a[:2,0,0])

[1 7]


In [72]:
print(a[1,1,1])

11


In [ ]:
a = np.array()
print()